sudo: required
services:
  - docker

before_install:
  - docker build -t jgaldrich/docker-react -f Dockerfile.dev .

script:
  #- docker run jgaldrich/docker-react npm run test -- --coverage
  - docker run -e CI=true jgaldrich/docker-react npm run test